services:
  2d-gsplat-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 2d-gsplat-dev-container
    image: 2dgsplat:1.0
    # user: 1010:1010 #terada
    volumes:
      # - /etc/passwd:/etc/passwd:ro
      # - /etc/group:/etc/group:ro
      - .:/root/2d-gs
      - ~/.ssh:/root/.ssh
      # ports:
      #   - "8087:8088"
    working_dir: /root/2d-gs
    tty: true
    network_mode: "host"
    # host gpu を使えるようにする設定　https://docs.docker.jp/compose/gpu-support.html
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
